version: '3.6'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - '5000:5000'

  cypress:
    build:
      context: .
      dockerfile: Dockerfile-cypress
    depends_on:
    - app
    network_mode: 'host'
